### PR TITLE
fix(android): bring back parent Dialog theme

### LINKED ISSUE #543: Android button text color irregular in Expo managed workflow app
# Bug report

## Summary
I’m using the react native community Date Time Picker in my managed workflow Expo app(Expo SDK Version 43.0.3)
I recently found out that on older Android phones, the text color of the module would render as white, thus not visible on white background.

This only happens when using display “spinner” and not the “calendar” (default) one. In spinner display, I have a green text color on recent Android and white on old ones. In calendar, I have a nice blue color.

I saw a lot of issues on their github to fix this, and all solutions include managing the style file in the android folder.

Another solution I tried was adding a “primaryColor” field in Expo config file, but this changed nothing.

Does someone know how to fix this issue, changing color or preventing it to render as white in a managed expo app?

## Reproducible sample code
[sample code for snack.expo](https://snack.expo.dev/@expo151388/rndatetimepicker-text-color)

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

## Environment info

`npx react-native info` output:

```bash
System:
    OS: macOS 11.0.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 63.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/local/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 3.5.2 (5.0.1 have same problem)

Android version: API29、30
Expo SDK version: 43.0.3

### LINKED ISSUE #678: Android Date Picker wrong background color on 6.5.1
# Bug report

## Summary

Hello, we are experiencing an Android bug on 6.5.1 where the date picker's background color changed.
Maybe we need to set it to a default for the picker?

| 6.5.0 | 6.5.1 |
|------| ------|
| 4835209c-378d-4ab1-a4b2-cd4fb18e95f4 | 8bf6d142-0f5f-447c-8a95-ec3ebe9723a9 |

## Reproducible sample code
I still don't have a reproducible sample outside of our private repo.

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

## Environment info

`npx react-native info` output:

```bash
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 90.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.2.4 - ~/.yvm/shim/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/fonz/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: 25.0.8775105
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 6.5.1

iOS / Android version: Android api 30

### PR DESCRIPTION
**Pull request by vonovak**
# Summary

closes #678, closes #543

also internally removes the `clock` and `calendar` modes because the `default` mode always (as far as I have seen) resolves to clock / calendar so having `default` and `spinner` is enough. I didn't remove them from the public api in case there's some issue, and also it'd be a breaking change.

Removing them simplifies code and also should fix #543 

## Test Plan

tested extensively locally

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅      |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

File: android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java [hunk 1]
```diff
@@ -30,4 +42,32 @@ public static void dismissDialog(FragmentActivity activity, String fragmentTag,
...
+		TypedValue typedValue = new TypedValue();
+		Resources.Theme theme = activity.getTheme();
+		theme.resolveAttribute(android.R.attr.textColorPrimary, typedValue, true);
+		@ColorRes int colorRes = (typedValue.resourceId != 0) ? typedValue.resourceId : typedValue.data;
+		@ColorInt int colorId = ContextCompat.getColor(activity, colorRes);
+		return colorId;
+	}
+
+	@NonNull
+	public static DialogInterface.OnShowListener ensureButtonsVisible(@NonNull Context activityContext, final AlertDialog dialog) {
```
Comment (vonovak) [inline android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java:56]: this will serve to allow customizing button text color in future

File: android/src/main/res/values-night/styles.xml [hunk 2]
```diff
@@ -1,9 +1,12 @@
 <resources xmlns:tools="http://schemas.android.com/tools">
+
+	<!-- color from https://m1.material.io/style/color.html#color-themes -->
 	<style name="SpinnerDatePickerDialog" parent="SpinnerDatePickerDialogBase">
-		<item name="colorPrimary">@android:color/white</item>
+		<item name="android:windowBackground">#424242</item>
```
Comment (capezzbr) [inline android/src/main/res/values-night/styles.xml:5]: nit, Why not referencing colors from `@android:color/`

File: android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java [hunk 3]
```diff
@@ -114,6 +115,7 @@ static DatePickerDialog createDialog(
     }
 
     final DatePicker datePicker = dialog.getDatePicker();
+	dialog.setOnShowListener(ensureButtonsVisible(activityContext, dialog));
```
Comment (capezzbr) [inline android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java:118]: nit, but your IDE indentation seem to be tabs and not spaces like the rest of these files

File: android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java (hunk 1 above)
Comment (capezzbr) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java:56]: nit, What about naming this method something like `styleButtons` or `updateButtonsStyle`?

**Review by capezzbr — APPROVED** [review]
I don't have a lot of expertise with Dialogs, but changes seem fine to me 👍

File: android/src/main/res/values-night/styles.xml (hunk 2 above)
Comment (vonovak) [reply android/src/main/res/values-night/styles.xml:5]: @capezzbr if you tell me what color to reference, I'll do it! 😅 
Maybe I'm blind but I didn't find the right color... and I'm surprised I need to define it, I though the theme would handle it for me...

File: android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java (hunk 3 above)
Comment (vonovak) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java:118]: yeah, the project is a mess when it comes to this... I need to add editorconfig and unify this across the project. iOS project also has it messed up 🙈

File: android/src/main/res/values-night/styles.xml (hunk 2 above)
Comment (capezzbr) [reply android/src/main/res/values-night/styles.xml:5]: Now that I look at this change closer,
> I thought the theme would handle it for me...
I am thinking the same, why would we need to re-define the window color, I'd assume it should come from the theme

Comment (capezzbr) [reply android/src/main/res/values-night/styles.xml:5]: Could it be that you don't have to explicitly create `values-night/styles.xml` since `Theme.AppCompat.DayNight.Dialog` will handle that?

Comment (capezzbr) [reply android/src/main/res/values-night/styles.xml:5]: From the official documentation https://developer.android.com/develop/ui/views/theming/darktheme

> ?android:attr/textColorPrimary This is a general purpose text color. It is near-black in Light theme and near-white in Dark themes. It contains a disabled state.

so in theory that value will change whether the user has enabled dark/light mode, and the app theme should reflect that

**Comment by vonovak** [comment]
> I don't have a lot of expertise with Dialogs, but changes seem fine to me 👍


@capezzbr did some more changes that should simplify things, have a look if you like 👍

File: android/src/main/res/values-night/styles.xml (hunk 2 above)
Comment (capezzbr) [reply android/src/main/res/values-night/styles.xml:5]: Yeah Android themes are kinda hard to nail down, I think overriding the color is a good solution for now. tbh I'd have expected the theme to take care of the background color and adapt primary colors too

**Review by capezzbr — APPROVED** [review]

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 6.5.3 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
